version: 1.0.{build}
image: Visual Studio 2019
configuration: Release
install:
- ps: >-
    cd src

    nuget restore JitBuddy.sln

    $env:JitBuddy_BUILD_NUMBER = ([int]$env:APPVEYOR_BUILD_NUMBER).ToString("000")
   
    $env:JitBuddy_VERSION_SUFFIX = ""

    $env:appveyor_nuget_push = 'false'

    if(-Not $env:APPVEYOR_PULL_REQUEST_NUMBER) {
      if($env:appveyor_repo_tag -eq 'True') {
        if($env:appveyor_repo_tag_name -match '^[0-9]') {
           $env:appveyor_nuget_push = 'true'
           $env:JitBuddy_VERSION_SUFFIX = ""
        }
        if($env:appveyor_repo_tag_name -eq 'latest') {
           $env:appveyor_nuget_push = 'true'
           $env:JitBuddy_VERSION_SUFFIX = "pre$env:JitBuddy_BUILD_NUMBER"
        }
      }
    }
build:
  project: src/JitBuddy.sln
  verbosity: minimal
before_package:
- cmd: >-
     msbuild /t:pack /p:VersionSuffix="%JitBuddy_VERSION_SUFFIX%" /p:Configuration=Release JitBuddy/JitBuddy.csproj
artifacts:
- path: src\JitBuddy\Bin\Release\*.nupkg
  name: JitBuddy Nugets
deploy:
- provider: NuGet
  api_key:
    secure: 7cthHh+wYWZjhqxaxR6QObRaRnstvFkQOY7MkxIsC5kpQEBlKZXuinf0IybbYxJt
  on:
    appveyor_nuget_push: true
